<script>
// Constants.vue
export default {
  CREATIVE:"Background Scenario: <br/> As a prominent online influencer specializing in work-life balance. You like to work remotely in different countries and experience different cultures.  You often work remotely from various countries to immerse yourself in different cultures. In addition ,You also enjoy the innovative experience that cutting-edge technology brings you at the airport.<br/> Creative Task Description: <br/> You are now collaborating with a world-renowned design team. The team's goal is to design the experience of a futuristic, innovative, high-tech airport in Tokyo  for the year 2050., and team decided to draw upon your extensive travel experience and sensitivity to cutting-edge technology to help design team brainstorm new ideas and initiate the proposals. The proposal will be divided into two parts.<br/>Part 1: Please propose a story of an ideal experience in the innovative airport. The story should focus on what kind of futuristic, high-tech services or products can be experienced in this airport, and what will be felt when you experience them. The futuristic, high-tech services or products can be creative and imaginary and don't need to consider the feasibility of any current technology or service; instead, focus on achieving your ideal visit to this high-tech airport in 2050. The story should be 150-200 words.<br/> Part 2: Create three catchy marketing slogans that encapsulate the unique futuristic experiences mentioned in your story.",
  PRACTICAL:"Background Scenario: <br/> As a prominent online influencer specializing in work-life balance. You like to work remotely in different countries and experience different cultures.  You often work remotely from various countries to immerse yourself in different cultures. In addition ,You also enjoy the innovative experience that cutting-edge technology brings you at the airport.<br/> Practical Task Description:</br>You are preparing to one post on your Facebook page to guide first-time travelers successfully passing through the complicated process at the airport. The FB post will be divided into two parts.</br>Part 1: List concise, step-by-step guide that a traveler needs to follow from the moment they arrive at the airport until they board their plane. The guide should be listed with concise and straightforward. Part 1 should be 150-200 words.</br>Part 2: highlight the the top five common errors travelers encounter at airports and offer the practical solution formatted as a Q&A."
}
</script>


